name: Build and Push UBUNTOOLS

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:
    inputs:
      force:
        description: 'Force build and push'
        required: false
        default: 'false'
      tools:
        description: 'space separated list APT install '
        required: false
        default: ''
      tag:
        description: 'the tag for the DOCKER image'
        required: false
        default: ''
  push:
    tags:
      - '*'

env:
  UBUNTU_LATEST_DIGEST: ${{ vars.UBUNTU_LATEST_DIGEST }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This gives write access to contents, needed for updating variables
      actions: write   # This gives write access to actions, needed for updating variables

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Get Current Digest
      id: get_digest
      run: |
        CURRENT_DIGEST=$(docker manifest inspect ubuntu:latest | jq -r '.manifests[0].digest')
        echo "CURRENT_DIGEST=${CURRENT_DIGEST}" >> $GITHUB_ENV

    - name: Compare Digests
      id: compare_digest
      run: |
        if [ "${{ env.UBUNTU_LATEST_DIGEST }}" != "${{ env.CURRENT_DIGEST }}" ]; then
          echo "Digest changed, proceeding with build"
          echo "DIGEST_CHANGED=true" >> $GITHUB_ENV
        else
          echo "Digest not changed, skipping build"
          echo "DIGEST_CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Set Force Build
      if: github.event.inputs.force == 'true' || startsWith(github.ref, 'refs/tags/')
      run: echo "DIGEST_CHANGED=true" >> $GITHUB_ENV

    - name: Set TOOL & TAG
      run: |
        TAG_MESSAGE=$(git tag -l --format='%(contents)' "${GITHUB_REF##*/}")
        echo "TOOLS=${TAG_MESSAGE}" >> $GITHUB_ENV
        echo "UT_TAG=latest" >> $GITHUB_ENV
        
    - name: Manual trigger - overriding TOOLS
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tools != ''
      run: |
        echo "TOOLS=${{github.event.inputs.tools}}" >> $GITHUB_ENV

    - name: Manual trigger - overriding TAG
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: | 
        echo "UT_TAG=${{github.event.inputs.tag}}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build --build-arg TOOLS="${{env.TOOLS}}" -t "viorelpe/ubuntools:${{env.UT_TAG}}" .

    - name: Build and push Docker image
      if: env.DIGEST_CHANGED == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: viorelpe/ubuntools:${{ github.ref_name }}
        build-args: TOOLS=${{ env.TOOLS }}

    - name: Update Digest Variable
      if: env.DIGEST_CHANGED == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        gh variable set UBUNTU_LATEST_DIGEST --repo ${{ github.repository }} --body "${{ env.CURRENT_DIGEST }}"
